<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BR0LSTG" failures="0" tests="3" name="Default test" time="9.394" errors="0" timestamp="2020-10-16T15:41:47 CDT">
  <testcase classname="com.TestCases.SignIn" name="@BeforeClass signupPage" time="1.18">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.Reusable.Reusable.click(Reusable.java:91)
at com.TestCases.SignIn.signupPage(SignIn.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeClass signupPage -->
  <testcase classname="com.TestCases.SignIn" name="@AfterClass closeExcel" time="-1.602880907251E9">
    <skipped/>
  </testcase> <!-- @AfterClass closeExcel -->
  <testcase classname="com.Reusable.Reusable" name="@AfterTest closeApp" time="-1.602880907252E9">
    <skipped/>
  </testcase> <!-- @AfterTest closeApp -->
  <testcase classname="com.TestCases.SignIn" name="verifyClickingCreateAccountwithblankEmailid" time="0.0">
    <skipped/>
  </testcase> <!-- verifyClickingCreateAccountwithblankEmailid -->
  <testcase classname="com.TestCases.SignIn" name="verifyAccountAlreadyExist" time="0.0">
    <skipped/>
  </testcase> <!-- verifyAccountAlreadyExist -->
  <testcase classname="com.TestCases.SignIn" name="CreateAccountForNewUser" time="0.0">
    <skipped/>
  </testcase> <!-- CreateAccountForNewUser -->
</testsuite> <!-- Default test -->
